name: Build FFmpeg SO

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y yasm nasm pkg-config wget unzip

      - name: Download FFmpeg
        run: |
          wget https://ffmpeg.org/releases/ffmpeg-4.4.tar.gz
          tar -xzf ffmpeg-4.4.tar.gz
          mv ffmpeg-4.4 ffmpeg

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
          unzip android-ndk-r26b-linux.zip
          echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r26b" >> $GITHUB_ENV

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-so
          path: output
